services:
  - type: web
    name: cricket-app
    env: ruby
    buildCommand: |
      bundle install &&
      cd frontend &&
      npm install &&
      npm run build &&
      cd .. &&
      cp -a frontend/build/. public/
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: RAILS_ENV
        value: production 